// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
// app/dashboard/layout.tsx
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import DashboardSidebar from "@/components/ui/dashboard/DashboardSidebar";
import DashboardHeader from "@/components/ui/dashboard/DashboardHeader";
import Providers from "@/Provider/Providers";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "My Dashboard",
  description: "Admin dashboard built with Next.js and Poppins font",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}  antialiased `}>
        <div className="flex gap-6 h-screen bg-[#E5E5E5]">
          {/* Sidebar */}

          <Providers>
            <DashboardSidebar />

            {/* Main Content Area */}
            <div className="flex-1 flex flex-col overflow-hidden">
              {/* Header */}
              <DashboardHeader />

              {/* Page Content */}
              <main className="flex-1 overflow-y-auto py-4 px-4 md:px- lg:px-">
              {/* <main className="flex-1 overflow-y-auto "> */}
                {children}
              </main>
            </div>
          </Providers>
        </div>
      </body>
    </html>
  );
}
